### ISSUE TITLE
Dmg mounted fail on El Capitan and Catalina

### ISSUE THREAD

**Issue by bw-development** [choll/packetpeeper#2]
Finder not able to mount PacketPeeper_2019-11-21.dmg. 

Fail with message "no mountable file system"

**Comment by choll** [comment]
Hi,

What is the md5 checksum of the dmg that you downloaded? It should be fbc41a136375cafcb70dfa1c973c6260.

Thanks
Chris

**Comment by choll** [comment]
closing ticket due to lack of response--please try downloading the dmg again as I expect the issue is that the download was corrupted
