### ISSUE TITLE
Loading capture file failed: Unsupported link-layer

### ISSUE THREAD

**Issue by peter-krijgsman** [choll/packetpeeper#4]
When opening a pcap file, the following error shows up: Loading capture file failed: Unsupported link-layer.
I can only choose to dismiss, so the file cannot be opened.

**Comment by choll** [comment]
Hi, on the command line could you please run `hexdump -n64 <path to your pcap>` then paste the results here? Alternatively you could attach the pcap if you are comfortable doing so. Thanks.

**Comment by choll** [comment]
Closed while waiting for further details (please feel free to reopen, seems GitHub only has open/closed states)
