### ISSUE TITLE
Unreadable text (white on white) in the dark mode

### ISSUE THREAD

**Issue by prantlf** [choll/packetpeeper#6]
On OSX 11.2.3, installed with `brew`:

```
❯ brew info packet-peeper
packet-peeper: 2019-12-17
https://packetpeeper.org/
/usr/local/Caskroom/packet-peeper/2019-12-17 (127B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/packet-peeper.rb
```

The hell mode looks well:

![grafik](https://user-images.githubusercontent.com/733193/125671555-258058b8-f5ce-4499-96a4-01ec29e90ad7.png)

In the dark mode, the text in the packet window is white on white:

![grafik](https://user-images.githubusercontent.com/733193/125671662-9ea19725-30fb-4590-a9ff-f78ec4e4660c.png)

When clicking on the white pane to make a selection, the text reveals:

![grafik](https://user-images.githubusercontent.com/733193/125671784-3567cfed-0e7d-4ac1-a7aa-d19a076734b1.png)

Maybe the background of than pane should be set to black?

**Comment by choll** [comment]
Will take a look, thanks for submitting a report.

**Comment by choll** [comment]
Please try https://github.com/choll/packetpeeper/releases/tag/2021-07-15

**Comment by choll** [comment]
Added a pull request for brew: https://github.com/Homebrew/homebrew-cask/pull/108491

**Comment by choll** [comment]
Closing the ticket---Please reopen if the new build has any problems, thanks.

**Comment by prantlf** [comment]
> Please try https://github.com/choll/packetpeeper/releases/tag/2021-07-15

Wow, it was quick! And it works great, thank you!

![grafik](https://user-images.githubusercontent.com/733193/125986971-d52a0bc6-9812-4f8b-8395-c24361b58dbf.png)

The red and blue colours in the reassembled HTTP stream could be a little lighter for a better contrast, but when going to the game mode by turning the table light off it gets better :-)

![grafik](https://user-images.githubusercontent.com/733193/125987547-0db3925e-925d-43f2-98fc-cc9e66b5ae1c.png)

**Comment by choll** [comment]
Hi, you're welcome. For fixing the dark blue try this build:

https://dev.azure.com/cholloway/68ac6105-64ab-477e-a88e-8a9bb93a0777/_apis/build/builds/187/artifacts?artifactName=drop&api-version=6.0&%24format=zip

If that looks OK I'll tag another release. Thanks.

**Comment by prantlf** [comment]
Yes, you nailed it! They new red and blue colours are very nicely readable in good light conditions, with a little light and in the darkness. No burning effect of a fully saturated colour any more. Thanks a lot!

![grafik](https://user-images.githubusercontent.com/733193/126038949-80f31165-01d6-41b7-9bd6-4817b01fd1c0.png)

**Comment by choll** [comment]
Great, I've made a new release with this change: https://github.com/choll/packetpeeper/releases/download/2021-07-18/PacketPeeper_2021-07-18.dmg. Thanks!
